Opetushallitus/hakurekisteri

core/src/main/scala/fi/vm/sade/hakurekisteri/integration/tarjonta/TarjontaActor.scala, web/src/main/scala/fi/vm/sade/hakurekisteri/web/kkhakija/KkHakijaResource.scala, web/src/test/scala/fi/vm/sade/hakurekisteri/rest/KkHakijaResourceSpec.scala
Käytetään Tarjonnan koulutus tietoja Haun tietojen sijaan
määriteltäessä ilmoittautumistiedot. Tämä ottaa kantaa siihen
tilanteeseen jossa haku on esimerkiksi syksyllä mutta, koulutus
alkaakin vasta syksyllä seuraavana vuonna. Tällöin aiemmin
ilmoittautumisiksi tuli kevät ja syksy eikä syksy ja kevät tulevia
vuosia.
Kattokee tarkasti etten hölömöillyt!!
https://jira.oph.ware.fi/jira/browse/BUG-908
=> BUG-908: Rajapinnan ilmoittautumiskaudet

src/main/scala/fi/vm/sade/hakurekisteri/integration/hakemus/IlmoitetutArvosanatTrigger.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/henkilo/oppijaNumeroRekisteri.scala, src/main/scala/fi/vm/sade/hakurekisteri/oppija/OppijaFetcher.scala, src/main/scala/fi/vm/sade/hakurekisteri/storage/ResourceActor.scala, src/main/scala/fi/vm/sade/hakurekisteri/suoritus/SuoritusQuery.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/ArvosanaResourceIntegrationSpec.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/henkilo/PersonOidsWithAliasesSpec.scala, src/test/scala/fi/vm/sade/hakurekisteri/suoritus/SuoritusJDBCActorSpec.scala
Bugi on semmoinen että kun Suresta ladataan käynnistyksen yhteydessä viimeisen 2 päivän aikana muokatut hakemukset, ja niiden hakijoille sitten ko. hakijan suoritukset yksi kerrallaan, niin siinä välitetään turhaan koko hakemussetin hakijoiden henkilöoidit mukaan, ja tämä tekee hausta turhaan raskan.
QA:n muokattujen hakemusten määrillä tämä ei näkynyt niin selvästi, että olisimme huomanneet asian, mutta tuotannossa se jumitti koko Suren.
Korjauksena varmistellaan eri tavoin, että JDBC-kerrokselle asti välitettävässä `PersonOidsWithAliases` -oliossa ei olisi kuin tarvittavien henkilöioidien linkitystieto mukana.
Samalla löytyi samanhenkinen palasteluun liittyvä TODO OppijaFetcheristä, joten korjasin senkin.
=> Fix for updating suoritus data of most recent applications

src/main/resources/suoritusrekisteri-oph.properties, src/main/scala/fi/vm/sade/hakurekisteri/hakija/HakijaActor.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/koodisto/KoodistoActor.scala, src/main/scala/fi/vm/sade/hakurekisteri/web/kkhakija/KkHakijaService.scala, src/test/scala/fi/vm/sade/hakurekisteri/acceptance/tools/HakeneetSupport.scala, src/test/scala/fi/vm/sade/hakurekisteri/koodisto/KoodistoActorSpec.scala
* Refactor rinnasteinen koodiarvo querying from koodisto to
1. query the koodiuri for the koodiarvo from koodisto
2. use that koodiuri to query the rinnasteinen koodiarvo from koodisto
in order to avoid error-prone koodiuri construction in KoodistoActor.
=> Refactor getRinnasteinenKoodiArvoQuery in KoodistoActor

src/main/scala/fi/vm/sade/hakurekisteri/integration/ytl/YtlActor.scala
Lisätietoa: https://jira.oph.ware.fi/jira/browse/BUG-1431
=> Jira BUG-1431: Sure tulkitsee yo-kokeen muuttuneen pakollisuustiedon eri suoritukseksi

pom.xml, src/main/scala/fi/vm/sade/hakurekisteri/tools/ItPostgres.scala, src/main/scala/fi/vm/sade/hakurekisteri/web/jonotus/Siirtotiedostojono.scala, src/main/scala/fi/vm/sade/hakurekisteri/web/rest/support/SecuritySupport.scala
Tämä korjaa Suren tiedonsiirron (esim https://virkailija.untuva.aws.opintopolku.fi/suoritusrekisteri/#/tiedonsiirto/kkhakeneet ) käyttämän valinta-tulos-service-pyynnön. Se meni pilviympäristöissä rikki, kun `X-Forwarded-For` -headerissa oli useamman IP-osoitteen lista. Eli tämä on vastaava korjaus kun on jo tehty valinta-tulos-serviceen ja valintalaskentakoostepalveluun.
=> OY-131 :  Read client IP address also from X-Real-IP header

src/main/resources/application.conf, src/main/resources/oph-configuration/suoritusrekisteri.properties.template, src/main/scala/fi/vm/sade/hakurekisteri/integration/cache/CacheFactory.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/cache/RedisUpdateConcurrencyHandler.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/cache/monadCache.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/koodisto/KoodistoActor.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/organisaatio/OrganisaatioActor.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/parametrit/ParameterActor.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/tarjonta/TarjontaActor.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/valintatulos/ValintaTulosActor.scala, src/main/scala/fi/vm/sade/hakurekisteri/web/hakija/HakijaResourceSupport.scala, src/test/resources/log4j.properties, src/test/resources/mock-data/organisaatio/organisaatio-1.2.246.562.10.165466228888.json, src/test/scala/fi/vm/sade/hakurekisteri/integration/FutureCacheSpec.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/RedisCacheSpec.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/organisaatio/OrganisaatioActorSpec.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/valintatulos/ValintaTulosActorWithRedisSpec.scala
Suoritusrekisterin cache-tiedon hallinnassa ei ole ollut rinnakkaisuuden hallintaa sen suhteen, kuka pääsee päivittämään cachea. Niinpä tietyn tiedon vanhennuttua sitä ollaan saatettua kysyä erittäin monen kysyvän threadin pyynnöstä taustajärjestelmästä (ks. esim Jira-tiketiltä https://jira.oph.ware.fi/jira/browse/BUG-1645 ).
Alkuperäisessä tiketissä puhutaan tarjonnasta, mutta samanlaista toimintaa on näkynyt esimerkiksi koodiston suhteen.
Korjauksessa pyritään pitämään kirjaa siitä, ketkä kaikki ovat pyytäneet jotakin tietoa cachesta, ja mikäli tietoa ei valmiiksi löydy cachesta, on tarkoitus, että vain yksi sitä kysyvistä säikeistä tekee tarvittavan pyynnön taustajärjestelmään ja palauttaa sitten tiedon kaikille muille.
Lisäksi olen yrittänyt tehdä thread poolien käyttöä …
=> BUG-1645 : Suoritusrekisteri tekee valtavasti kyselyjä backendeihin

src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/ArvosanaMyonnettyParser.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiArvosanaTrigger.scala, src/test/resources/fi/vm/sade/hakurekisteri/integration/koski/henkilo_without_arviointipvm_from_koski.json, src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/ArvosanaMyonnettyParserSpec.scala
Tallennetaan arvosanalle myöntöpäivämäärä vain tämän ollessa myöhemmin kuin suorituksen valmistumispäivämäärä. Tällöin korotukset näkyvät oikein ja tulevat skipatuiksi laskennassa sikäli kun ne on myönnetty laskennan alun jälkeen.
=> BUG-1771 : ylimääräiset Koski-arvosanojen myöntöpäivämäärät pois

src/main/resources/suoritusrekisteri-oph.properties, src/main/scala/fi/vm/sade/hakurekisteri/integration/valintarekisteri/ValintarekisteriActor.scala, src/main/scala/fi/vm/sade/hakurekisteri/web/kkhakija/KkHakijaService.scala, src/test/resources/suoritusrekisteri-oph.properties, src/test/scala/fi/vm/sade/hakurekisteri/web/kkhakija/KkHakijaServiceSpec.scala
This way we can get all lukuvuosimaksu data for a single
hakukohde with a single fast query to valinta-tulos-service.
Previously, if we had e.g. 5000 candidates applying in this
hakukohde and a 1000 other different hakukohdes in their
applications, 1000 requests would be required.
Here, taking to use the new API in valinta-tulos-service : https://github.com/Opetushallitus/valinta-tulos-service/pull/88
=> BUG-1758 : Use new more performant API

src/main/scala/fi/vm/sade/hakurekisteri/integration/cache/CacheFactory.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/cache/monadCache.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/koodisto/KoodistoActor.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/organisaatio/OrganisaatioActor.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/tarjonta/TarjontaActor.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/valintatulos/SijoitteluTulos.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/valintatulos/ValintaTulosActor.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/FutureCacheSpec.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/RedisCacheSpec.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/valintatulos/ValintaTulosActorWithRedisSpec.scala
Ongelma:
Luokkien Redikseen kirjoituksessa käytetään Javan serialisaatiota, mikä luo automaattisesti serialVersionUID:n. Kun luokalle esim. lisätään metodi, sen serialVersionUID muuttuu, jolloin deserialisointi ei enää onnistu. Tämän exceptionin havaitseminen ei onnistu käytetyllä ajurilla.
Ratkaisu:
Redis cacheen tallennetaan serialVersionUID (Javan automaattisesti generoima). Cachen initialisoinnissa (JARin käynnistyessä) tarkistetaan, onko cacheen kirjoitettu serialVersionUID sama kuin nyt JARissa olevan luokan serialVersionUID. Jos ei, tiedetään että luokka on muuttunut, jolloin tyhjennetään koko cache ja tallennetaan sinne uusi serialVersionUID.
=> BUG-1733  muuttuneen luokan redis-cachen tyhjennys

.travis.yml, package.json, pom.xml, src/main/scala/fi/vm/sade/hakurekisteri/tools/ItPostgres.scala, src/test/resources/front-mock-files/test/lib/mocha.js, src/test/resources/front-mock-files/test/runner.html, src/test/scala/fi/vm/sade/hakurekisteri/mocha/HakureRekisteriMochaTest.scala
- use Headless Chrome instead of phantomjs, via mocha-headless-chrome module. It turned out that phantomjs tests were not executing as part of  `mvn test`. Headless Chrome tests are executing. Also `mocha.js` had to be upgraded. Old version was causing timeout expiration during e2e tests.   
- ItPostgres.scala modified to behave differently if the database already exists, as in Travis environment. Introduced is the system property `postgresRunningOnPort` so that ItProgress knows whether there is already a database running.
=> SEC-64 Use headless-chrome instead of phantomjs

src/main/scala/fi/vm/sade/hakurekisteri/integration/CasActor.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/VirkailijaRestClient.scala
Default of one minute is too little for loading large
haku results from valinta-tulos-service.
=> BUG-1979 : Fix timeout setting

src/main/scala/fi/vm/sade/hakurekisteri/integration/ytl/YtlFileSystem.scala
It uses default credentials provider if no credentials provider is specified; this is the desired behavior.
With default credentials, the S3 bucket is accessed using ECS Task Role instead of the EC2 Instance Role. The latter has been used in our AWS environments until now, but we want to minimize the instance role's permissions, and instead make all containerized services use their own task roles.
=> Do not use instance profile credentials with s3 client

src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiUtil.scala, src/main/scala/fi/vm/sade/hakurekisteri/web/koski/KoskiImporterResource.scala, src/main/scala/support/Integrations.scala
AIemmin koskiImporterResourcea ("mahtikäsky") pystyi käyttämään vaikka koski-integraatio olisi muuten ollut suljettuna ympäristössä. Tämän myötä ei enää pysty.
=> Ksk 2 sulkeminen

pom.xml, src/main/scala/fi/vm/sade/hakurekisteri/integration/hakemus/HakemusBasedPermissionCheckerActor.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/hakemus/HakemusBasedPermissionCheckerActorSpec.scala
Isoissa hakukohteissa hakemuspohjaiset oikeustarkistukset (jotka toteutettiin SEC-68 :ssa) aiheuttavat suorituskykyongelmia. Niitä helpottaa, jos ei tarvitse tarkistaa oikeuksia joka kerta sekä haku-appista että Atarusta, vaan nopein true-vastaus riittää.
=> BUG-1983 : oppija- rajapinta toimii isoille määrille vain rekisterinpitäjälle

.gitignore, src/main/scala/fi/vm/sade/hakurekisteri/integration/valintatulos/ValintaTulosActor.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/valintatulos/ValintaTulosActorSpec.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/valintatulos/ValintaTulosActorWithRedisSpec.scala
`HakuActor` has the responsibility to refresh the cache which is within `ValintaTulosActor`. This refresh operation will simply reload *all* active haku results. The time between two refreshes (`valintatulosRefreshTimeHours`) *must be shorter* than the cache expiration time (`valintatulosCacheHours`), so that it never happens that active haku results are expired. 
Problem was before when `ValintaTulosActor` was not updating the active haut that are already in cache, and they could unnecessarily expire.
=> BUG-1981 valinta tulos cache improvement

src/main/scala/fi/vm/sade/hakurekisteri/hakija/representation/XMLHakija.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/hakemus/Hakupalvelu.scala, src/main/scala/fi/vm/sade/hakurekisteri/suoritus/Suoritus.scala
If better information not available,
show an empty field instead of the
previously-shown 1970.
=> Get todistusvuosi from koostedata if available.

src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiService.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/koskiDomain.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/valintatulos/ValintaTulosActor.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiServiceSpec.scala
Lisätty uudelleenyrityksiä (oletus 3 kpl/batch, 10 sekunnin odotuksen jälkeen) epäonnistuneille koski-tiedonhauille ja niihin liittyville onr-aliaspyynnöille. 
Parannettu yleisesti batcheittain-haun logitusta. Logitetaan myös haun oid, mikäli kyse on jonkin aktiivisen haun tietojen yöllisestä päivityksestä.
=> Bug 2157 koskibatchienvirheet

src/main/scala/fi/vm/sade/hakurekisteri/integration/organisaatio/OrganisaatioActor.scala
Jos organisaatiopalvelun rajapinta palauttaa käyttöoikeustarkistukselle 403-statuksisen kutsun, jätetään siihen liittyvä organisaatio huomioimatta käyttöoikeuspäättelyssä. 
Tähän liittyen tehty muutos organisaatiopalveluun, https://github.com/Opetushallitus/organisaatio/pull/149, jonka asentaminen on vaatimuksena tämän toiminnalle.
=> Bug 2164 organisaatiot

src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandler.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandlerTest.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/pk_kaksi_kasiluokkaa.json
Ei ahdistuta duplikaattiluokkasuorituksista, joita syntyy esimerkiksi silloin jos henkilö jää luokalle ja suorittaa saman luokan uudelleen samassa koulussa. 
Lisätty testi.
=> BUG-2177 Allow duplicate perusopetusluokkas. Add a test.

package-lock.json, src/main/resources/webapp/templates/muokkaa-tiedot.html, src/main/scala/fi/vm/sade/hakurekisteri/web/integration/virta/VirtaSuoritusResource.scala, src/test/scala/fi/vm/sade/hakurekisteri/rest/VirtaSuoritusResourceSpec.scala
Nyt suoritustietojen haku virrasta tapahtuu ensisijassa henkilön hetulla, mikäli sellainen on määritelty requestiin. Muussa tapauksessa (duplikaattihenkilö) kysytään ensin ONR:ltä master-henkilö, jolla suoritustiedot voidaan hakea duplikaatille.
=> BUG-2117: Suren näytä tiedot virta-järjestelmästä painike ei toimi

.gitignore, src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandler.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandlerTest.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_7_8_tuleva_ei_lasna.json, src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_7_8_valmistava_ei_peruskoulun_paattanyt.json
Fixes:
- OY-4208: filtering order was incorrect, so that perusopetuksen oppiaineen suoritus without finished perusopetuksen suoritus blocked saving 7-8-valmistava data
- OY-4212: future absences were incorrectly considered in determining saving of 7-8-valmistava data
=> OY-4208 & OY-4212 7-8-valmistava filtering fixes

src/main/scala/fi/vm/sade/hakurekisteri/web/kkhakija/KkHakijaService.scala
For some reason new kkhakijat v5 field hakemukset->hakukohteenKoulutukset->johtaaTutkintoon was accidentally added to v1-v4 responses, causing validation errors on external clients. Return it only with v5 responses.
=> OY-4267 Drop johtaaTutkintoon from old APIs

.gitignore, src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandler.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiUtil.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandlerTest.scala
VALMA-suoritukset from Koski should not be stored if their total scope is <30 osp even when they are finished - because at that point that's all there will be.
This logic was apparently added some point in 2019 according to logs, but later removed either accidentally or due to a reason. Now it's required again in either case.
=> OY-4780 restore discarding <30 osp VALMA even when ready

src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandler.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiSuoritusArvosanaParser.scala, src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/koskiDomain.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandlerTest.scala, src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_perusopetus_kesken_jaanyt_9luokalle.json, src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_perusopetus_valmis_erityinen_jaanyt_9luokalle.json, src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_perusopetus_valmis_jaanyt_9luokalle.json
OY-4825 ei huomioida koskidatan jääluokalle-tietoa 9-luokalla jos on valmis perusopetuksen oppimäärä.
Poistettu myös hieman kuollutta koodia.
=> Valmis perusopetuksen suorituksen pitää jyrätä 9-luokan jääluokalle-tieto
