- core/src/main/scala/fi/vm/sade/hakurekisteri/integration/tarjonta/TarjontaActor.scala
- core/src/test/scala/fi/vm/sade/hakurekisteri/tarjonta/TarjontaActorSpec.scala
- web/src/test/scala/fi/vm/sade/hakurekisteri/rest/KkHakijaResourceSpec.scala
SURE hake nykyään Tarjonnasta valmiiden hakujen lisäksi myös julkaistut jatkotutkintohaut.
> Feature include valmiit jatkotutkintohaut

- src/main/scala/fi/vm/sade/hakurekisteri/web/jonotus/Siirtotiedostojono.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/kkhakija/KkExcelUtilV3.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/kkhakija/KkHakijaService.scala
siirtotiedoston formaatti korjattu
> BUG-1405 liitteet poistettu v1-jsonista ja siirtotiedosto korjattu

- src/main/scala/fi/vm/sade/hakurekisteri/web/kkhakija/KkHakijaService.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/hakemus/json/applicationsByPersonOid.json
- src/test/scala/fi/vm/sade/hakurekisteri/rest/KkHakijaResourceSpec.scala
Lisätietoa: https://jira.oph.ware.fi/jira/browse/BUG-1442
> asiointikieli is now mapped to either 1, 2, 3 or 9

- src/main/scala/fi/vm/sade/hakurekisteri/web/kkhakija/KkHakijaService.scala
Lisätietoa: https://jira.oph.ware.fi/jira/browse/BUG-1448
> Passed hakemus.julkaisuLupa to hakemukset.map

- src/main/resources/coffee/configure.coffee
- src/main/resources/coffee/controller-hakeneet.coffee
- src/main/resources/webapp/templates/hakeneet.html
Korjattu tilanne jossa 565 matchaa sekä hakukohteet 565 että 1565 ja joudutaan haaraan controller-hakeneet.coffee:450
Lisäksi muutettu muuttujanimiä vastaamaan paremmin todellisuutta (sisältävätkö koodin vai objektin)
> Bug 1476 tiedonsiirron hakukohdekoodi

- src/main/resources/coffee/muokkaa-arvosana-yo.coffee
- src/main/scala/fi/vm/sade/hakurekisteri/arvosana/ArvosanaActor.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/ytl/YtlActor.scala
Lisätietoa: https://jira.oph.ware.fi/jira/browse/BUG-1431
> BUG-1431: Sure tulkitsee yo-kokeen muuttuneen pakollisuustiedon eri suoritukseksi

- src/main/resources/coffee/controller-hakeneet.coffee
- src/main/resources/webapp/templates/hakeneet.html
- src/main/scala/fi/vm/sade/hakurekisteri/integration/VirkailijaRestClient.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/kooste/KoosteService.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/jonotus/AsiakirjaResource.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/VirkailijaRestClientSpec.scala
näytetään asiakirjan muodostumisessa tapahtuneet virheet paremmin käyttäjälle
> Bug 1494 tiedonsiirto virheet

- pom.xml
- src/main/scala/fi/vm/sade/hakurekisteri/rest/support/HakijatExcelWriter.scala
- src/test/scala/fi/vm/sade/hakurekisteri/tools/ExcelTools.scala
Use the sama java-poi conditional dangerous cell content prefixing as in haku-app and valintaperusteet.
https://jira.oph.ware.fi/jira/browse/SEC-48
https://github.com/Opetushallitus/java-utils/blob/master/java-poi/src/main/java/fi/vm/sade/javautils/poi/OphCellStyles.java#L35-L50
> SEC-48  excel injection

- src/main/scala/fi/vm/sade/hakurekisteri/hakija/HakijaActor.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/organisaatio/OrganisaatioActor.scala
logitetaan ja heitetään virhettä/failed futurea eteenpäin jos tunniste on tyhjä
> BUG-1609 tyhja oid

- src/main/resources/suoritusrekisteri-oph.properties
- src/main/scala/ScalatraBootstrap.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/hakemus/HakemusBasedPermissionCheckerActor.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/integration/virta/VirtaSuoritusResource.scala
- src/main/scala/support/Integrations.scala
- src/test/resources/suoritusrekisteri-oph.properties
Katso https://github.com/Opetushallitus/ataru/pull/435
> Hle 258  authorization based on ataru

- src/main/resources/oph-configuration/suoritusrekisteri.properties.template
- src/main/scala/ScalatraBootstrap.scala
- src/main/scala/fi/vm/sade/hakurekisteri/Config.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/hakija/HakijaResourceSupport.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/kkhakija/KkHakijaResourceV2.scala
- src/test/scala/fi/vm/sade/hakurekisteri/MockConfig.scala
And make it configurable for future generations.
Details: https://jira.oph.ware.fi/jira/browse/BUG-1684
> BUG-1684 : Increase API timeout

- src/main/scala/fi/vm/sade/hakurekisteri/web/hakija/HakijaResource.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/hakija/HakijaResourceSupport.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/hakija/HakijaResourceV2.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/hakija/HakijaResourceV3.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/hakija/HakijaService.scala
- src/test/scala/fi/vm/sade/hakurekisteri/acceptance/tools/HakeneetSupport.scala
- src/test/scala/fi/vm/sade/hakurekisteri/rest/HakijaResourceSpec.scala
- src/test/scala/fi/vm/sade/hakurekisteri/rest/HakijaResourceSpecV2.scala
- src/test/scala/fi/vm/sade/hakurekisteri/rest/HakijaResourceSpecV3.scala
Assuming that boot organisaatio ja taku are mandatory parameters, just like in UI.
> BUG-1718 Suren hakijat rajapintaan parametrien validointi

- src/main/scala/fi/vm/sade/hakurekisteri/ensikertalainen/EnsikertalainenActor.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/hakemus/HakemusService.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/hakemus/Hakupalvelu.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/hakemus/HakemusServiceSpec.scala
Katso https://github.com/Opetushallitus/ataru/pull/592
> Tieto suoritetusta korkeakoulututkinnosta atarusta

- src/main/scala/fi/vm/sade/hakurekisteri/integration/hakemus/HakemusService.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/hakemus/Hakupalvelu.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/kkhakija/KkHakijaService.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/hakemus/HakemusServiceSpec.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/hakemus/json/ataruApplications.json
- src/test/scala/fi/vm/sade/hakurekisteri/web/kkhakija/KkHakijaServiceSpec.scala
Katso myös https://github.com/Opetushallitus/ataru/pull/735
> Hakukelpoisuus ataru hakemukselta

- src/main/scala/fi/vm/sade/hakurekisteri/integration/virta/VirtaActor.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/virta/VirtaClient.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/virta/VirtaQueue.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/integration/virta/VirtaResource.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/virta/VirtaClientSpec.scala
Lisätty tiketin ulkopuolelta myös rajapinta yhden oppijan virtatietojen haulle
> Bug 1234 valipaivafix

- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandler.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiSuoritusArvosanaParser.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandlerTest.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_aloitus_deadlinepvm_jalkeen.json
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_pk_eronnut_valmistumispaivamaara.json
Pieni korjaus Koski-sure-integraatioon:
- Ei kaadu jos suorituksen tallennuksessa tulee virhe
- Keskeytyneeseen ysiluokkaan oikea valmistumispäivä
> Ksk 1 fix exception handling

- src/main/resources/oph-configuration/suoritusrekisteri.properties.template
- src/main/scala/fi/vm/sade/hakurekisteri/Config.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/henkilo/oppijaNumeroRekisteri.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiService.scala
- src/main/scala/support/Integrations.scala
- src/test/resources/oph-configuration/common.properties
- src/test/scala/fi/vm/sade/hakurekisteri/mocha/HakureRekisteriMochaTest.scala
Haetaan oideja 5000 batcheissä.
> BUG-1965 : Get oids with 5000 oid batches

- src/main/resources/oph-configuration/suoritusrekisteri.properties.template
- src/main/scala/fi/vm/sade/hakurekisteri/integration/hakemus/HakemusService.scala
- src/main/scala/fi/vm/sade/hakurekisteri/rest/support/HakijatExcelWriter.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/rest/support/DownloadSupport.scala
- src/main/scala/support/Integrations.scala
- src/test/scala/fi/vm/sade/hakurekisteri/rest/HakijaResourceSpec.scala
- src/test/scala/fi/vm/sade/hakurekisteri/rest/HakijaResourceSpecV2.scala
- src/test/scala/fi/vm/sade/hakurekisteri/tools/ExcelTools.scala
Pilkottu kutsut haku-appiin ja ataruun, jotta voi hakea suuriakin hakukohderyhmiä, ja siirrytty XLSX-tiedostoihin joihin mahtuu enemmän rivejä.
> BUG-1963  excel hakukohderyhmalle

- src/main/scala/fi/vm/sade/hakurekisteri/integration/henkilo/oppijaNumeroRekisteri.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandler.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiOpiskelijaParser.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiService.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiSuoritusArvosanaParser.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiUtil.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/koskiDomain.scala
- src/main/scala/support/Integrations.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiActorSpec.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandlerTest.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_erikoisammattitutkinto.json
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_lasnaolopaattely.json
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_peruskoulu_kesken_nelonen.json
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_peruskoulu_s_suorituksia.json
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_tuntematon_komo.json
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_valma_alku_01082019.json
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_valma_loma_ei_lasnaoloa.json
- Filtteröinti tulevaisuudessa alkaviin suorituksiin
- Filtteröinti suorituksiin, joilla ei löydy läsnäolotietoa
- Kymppiluokkien arvosanojen tallennus aina.
- Korjattu randomisti feilaava deleteOpiskelija -ongelma
> Ksk_1 filter future suoritukset always save kymppiluokka

- src/main/scala/fi/vm/sade/hakurekisteri/integration/ytl/YtlHttpFetch.scala
There seems to be a race condition if a recently
put file is read immediately after putting it.
We can just read the file contents in memory and
give separate handles to the in-memory array for
storing to S3 for debugging and for parsing and
storing to database.
Even with a batch size of 50 000, the size of each
zip file stayed under six megabytes, so buffering
them in memory one at a time should not pose problems.
> BUG-1990 : Use downloaded content directly

- src/main/scala/fi/vm/sade/hakurekisteri/integration/CasActor.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/VirkailijaRestClient.scala
https://jira.oph.ware.fi/jira/browse/BUG-1958
> BUG-1958 - Suoritusrekisteri antaa välillä virheitä huonon istunnonhallinnan takia

- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiSuoritusArvosanaParser.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandlerTest.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_valinnaisia_aidinkielia.json
Järjestys kuntoon ja kantaan tallennus.
> KSK-1_save_vain_numeroarvosanat : Added some numbers to test.

- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandler.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiSuoritusArvosanaParser.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandlerTest.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_aik_perusopetus_poo.json
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_aik_perusopetus_poo_useita.json
- Tallennetaan vain oppiaineen arvosanat, ei kurssien arvosanoja
- Tallennetaan, kun oppiaineen suoritus on merkitty hyväksytyksi riippumatta opiskeluoikeuden tilasta.
> Ksk-1 Perusopetuksen oppiaineen oppimäärä

- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/IKoskiService.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandler.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiService.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiSuoritusArvosanaParser.scala
- src/main/scala/fi/vm/sade/hakurekisteri/web/koski/KoskiImporterResource.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/03_06_debug.json
Kts. commit-viestit, pitäisi olla kuvaavia ja toisistaan irrallisia.
> Ksk pikkukorjauksia

- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandler.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandlerTest.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/VALMA_22_op_valmis.json
Kosken tiloista riippumaton päättely:
30p tai yli: VALMIS
jos alle, KESKEN ennen deadlinea ja KESKEYTYNYT deadlinen jälkeen.
> Tallennetaan kaikki Koskesta löytyvät valma-suoritukset.

- src/main/scala/fi/vm/sade/hakurekisteri/arvosana/Arvosana.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandler.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandlerTest.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_arvosanat_version_1.json
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/koskidata_arvosanat_version_2.json
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/valinnaiset_4_kuvataidetta_3_musiikkia_after.json
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/valinnaiset_4_kuvataidetta_3_musiikkia_before.json
Changed arvosanas are updated, non-changed are not touched.
Previously, non-changeds were deleted and re-inserted every time.
Now, only arvosanas that do not exist in Koski anymore are deleted.
> KSK-5 Add new handling for arvosanas from Koski

- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiService.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiSuoritusArvosanaParser.scala
- src/main/scala/fi/vm/sade/hakurekisteri/integration/koski/koskiDomain.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/KoskiDataHandlerTest.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/koski/json/yksilollistetty_toiminta_alueittain_uusi_muoto.json
Old style also still works.
Added a test.
> OY-371 Also handle new json structure for alueellinen yksilollistaminen

- src/main/scala/fi/vm/sade/hakurekisteri/hakija/HakijaActor.scala
- src/test/scala/fi/vm/sade/hakurekisteri/integration/ytl/YtlIntegrationSpec.scala
Testikorjaus ei varsinaisesti liity tähän bugiin, mutta korjaus menee kätevästi tässä samalla sisään. Testi oli hajonnut itsekseen.
> Bug 2195 harkinnanvaraiset hyvaksytyt exceliin

- src/main/scala/fi/vm/sade/hakurekisteri/hakija/HakijaActor.scala
Nopea fiksi puuttuvaan filtteröintiin
> Use filter for Hakija query v5 as well

- pom.xml
- korjattu lokitusta niin, että access-, app- ja audit-lokit menee omiin lokitiedostoihinsa
- poistettu "turhia" dependency exclusioneja
> OY-5089: suren lokituksen korjaus
